### ISSUE TITLE
Make README about the design system instead of Upstream

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-design-system#3]
There's lots of references to Upstream. Eventually could make the README more built out for the Design System, but for now probably can just strip out most things from it.

**Comment by rudolfs** [comment]
Did it in:
https://github.com/radicle-dev/radicle-design-system/commit/cbf2def71fda0c02e5c658337bf9f3b1abfcc19e
https://github.com/radicle-dev/radicle-design-system/commit/7b2c9efa71081c7600bbc73ce6eefac673b202d8
